### ISSUE TITLE
Acknowledge the game engine series from the Cherno

### ISSUE THREAD

**Issue by 0xworks** [TheSpectreZ/Nexus#31]
I appreciate that this engine is your own take on the game engine series, and is not just a straight copy of the Hazel game engine.  However, it is clearly inspired by the Hazel game engine series, and I think some acknowledgement of this in the project's readme would be appropriate.

**Comment by TheSpectreZ** [comment]
Thanks!

**Comment by 0xworks** [comment]
👍
